import { TradingCard, CardStoreInventory, HobbyStore } from './types';
import { calculateHaversineDistanceKm, DEFAULT_SINGAPORE_COORDS } from './utils/geo';

export const USER_CURRENT_LOCATION = 'City Hall, Central Singapore';

/**
 * Directory of Singapore hobby card stores with verified coordinates and public-transport accessibility info.
 * Every hobby store has latitude and longitude coordinates.
 */
export const HOBBY_STORES_DIRECTORY: Record<string, HobbyStore> = {
  'store-1': {
    id: 'store-1',
    name: 'Merlion Card Sanctum',
    location: '180 Bencoolen St, #02-15',
    neighborhood: 'Bugis / Rochor',
    latitude: 1.3015,
    longitude: 103.8528,
    publicTransit: {
      nearestMrt: 'Rochor MRT (DT13) & Bugis MRT (EW12/DT14)',
      mrtDistance: '150m (2 min walk from Rochor Exit A)',
      busServices: 'Buses 56, 64, 65, 131, 147, 166 (Stop: Aft Sim Lim Sq)',
      accessibilitySummary: 'Step-free passenger lift access to Level 2 from Bencoolen Street entrance, sheltered walkway from Rochor MRT',
    },
    sellerRating: 4.9,
    ratingCount: 312,
    verified: true,
    openingHours: '12:00 PM – 9:00 PM Daily',
    contactNumber: '+65 6235 1198',
  },
  'store-2': {
    id: 'store-2',
    name: 'Apex Games & Collectibles',
    location: '14 Scotts Rd, #03-88 Far East Plaza',
    neighborhood: 'Orchard',
    latitude: 1.3073,
    longitude: 103.8336,
    publicTransit: {
      nearestMrt: 'Orchard MRT (NS22/TE14)',
      mrtDistance: '350m (4 min walk from Exit 1)',
      busServices: 'Buses 5, 54, 105, 124, 132, 143, 162, 518 (Stop: Far East Plaza)',
      accessibilitySummary: 'Central atrium accessible lifts, barrier-free access from Scotts Road street-level taxi drop-off',
    },
    sellerRating: 4.8,
    ratingCount: 184,
    verified: true,
    openingHours: '11:30 AM – 9:00 PM Daily',
    contactNumber: '+65 6734 8820',
  },
  'store-3': {
    id: 'store-3',
    name: 'Paya Lebar Card Guild',
    location: '60 Paya Lebar Rd, #B1-06 Paya Lebar Square',
    neighborhood: 'Paya Lebar',
    latitude: 1.3188,
    longitude: 103.8925,
    publicTransit: {
      nearestMrt: 'Paya Lebar MRT (EW8/CC9 Interchange)',
      mrtDistance: '50m (Direct basement link from Exit A/B)',
      busServices: 'Buses 24, 28, 43, 70, 76, 134, 135, 154, 155 (Stop: Paya Lebar Stn)',
      accessibilitySummary: 'Direct barrier-free underground link from MRT concourse directly into Basement 1 shopping level',
    },
    sellerRating: 4.9,
    ratingCount: 420,
    verified: true,
    openingHours: '11:00 AM – 9:30 PM Daily',
    contactNumber: '+65 6842 5590',
  },
  'store-4': {
    id: 'store-4',
    name: 'Redhill Hobby Deck',
    location: '1 Jalan Merah Saga, #01-44',
    neighborhood: 'Bukit Merah',
    latitude: 1.2895,
    longitude: 103.8168,
    publicTransit: {
      nearestMrt: 'Redhill MRT (EW18)',
      mrtDistance: '250m (3 min walk from Exit A)',
      busServices: 'Buses 32, 33, 64, 120, 132, 145, 147, 196 (Stop: Opp Redhill Stn)',
      accessibilitySummary: 'Street-level ground floor shop with zero steps, tactile paving, and wide automated entrance',
    },
    sellerRating: 4.6,
    ratingCount: 75,
    verified: false,
    openingHours: '1:00 PM – 8:30 PM (Closed Mon)',
    contactNumber: '+65 6479 2311',
  },
  'store-5': {
    id: 'store-5',
    name: "Dragon's Vault TCG",
    location: '138 Jurong Gateway Rd, #02-337',
    neighborhood: 'Jurong East',
    latitude: 1.3338,
    longitude: 103.7436,
    publicTransit: {
      nearestMrt: 'Jurong East MRT (NS1/EW24 Interchange)',
      mrtDistance: '250m (3 min walk from Exit A via J-Walk)',
      busServices: 'Jurong East Bus Interchange (Buses 41, 49, 51, 66, 78, 79, 97, 98, 143, 197, 333)',
      accessibilitySummary: 'Connected via fully sheltered, barrier-free J-Walk elevated pedestrian walkway with ramps and lifts',
    },
    sellerRating: 4.7,
    ratingCount: 96,
    verified: true,
    openingHours: '12:00 PM – 9:00 PM Daily',
    contactNumber: '+65 6563 7741',
  },
  'store-6': {
    id: 'store-6',
    name: 'Golden Oasis Hobby Hub',
    location: '10 Tampines Central 1, #04-18',
    neighborhood: 'Tampines',
    latitude: 1.3538,
    longitude: 103.9452,
    publicTransit: {
      nearestMrt: 'Tampines MRT (EW2/DT32 Interchange)',
      mrtDistance: '120m (2 min walk from Exit C/D)',
      busServices: 'Tampines Bus Interchange (Buses 3, 10, 15, 20, 23, 27, 29, 31, 67, 291, 292, 293)',
      accessibilitySummary: 'Mall equipped with barrier-free passenger elevators directly connecting MRT level to Level 4',
    },
    sellerRating: 4.8,
    ratingCount: 210,
    verified: true,
    openingHours: '11:00 AM – 9:30 PM Daily',
    contactNumber: '+65 6788 1205',
  },
};

/**
 * Creates a card inventory item populated with store coordinates and accessibility details.
 */
function createStoreInventory(
  storeKey: keyof typeof HOBBY_STORES_DIRECTORY,
  price: number,
  quantity: number,
  condition: 'Near Mint' | 'Lightly Played'
): CardStoreInventory {
  const store = HOBBY_STORES_DIRECTORY[storeKey];
  // Calculate initial default straight-line distanceKm using Haversine formula from Central Singapore reference
  const distanceKm = calculateHaversineDistanceKm(
    DEFAULT_SINGAPORE_COORDS.latitude,
    DEFAULT_SINGAPORE_COORDS.longitude,
    store.latitude,
    store.longitude
  );

  return {
    storeId: store.id,
    storeName: store.name,
    location: store.location,
    neighborhood: store.neighborhood,
    latitude: store.latitude,
    longitude: store.longitude,
    publicTransit: store.publicTransit,
    distanceKm,
    price,
    quantity,
    condition,
    verifiedSeller: store.verified,
    sellerRating: store.sellerRating,
    ratingCount: store.ratingCount,
  };
}

export const CARDS_DATA: TradingCard[] = [
  {
    id: 'card-001',
    name: 'Astral Sorceress',
    subtitle: 'Weaver of Constellations',
    inkColor: 'Amethyst',
    rarity: 'Legendary',
    cardType: 'Character',
    cost: 7,
    strength: 5,
    willpower: 6,
    lore: 3,
    marketPrice: 48.50,
    totalQuantity: 24,
    cardNumber: '042/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Starfall Cascade',
    abilityText: 'When you play this character, you may draw 2 cards and return one opposing character to their player’s hand.',
    flavorText: '“The heavens do not merely foretell fate; they write it into the ink.”',
    artId: 'astral_sorceress',
    stores: [
      createStoreInventory('store-1', 46.00, 5, 'Near Mint'),
      createStoreInventory('store-2', 47.50, 3, 'Near Mint'),
      createStoreInventory('store-3', 45.00, 8, 'Near Mint'),
      createStoreInventory('store-4', 49.00, 2, 'Lightly Played'),
      createStoreInventory('store-5', 52.00, 6, 'Near Mint'),
    ],
  },
  {
    id: 'card-002',
    name: 'Sunlit Dragonling',
    subtitle: 'Ember Guardian',
    inkColor: 'Ruby',
    rarity: 'Super Rare',
    cardType: 'Character',
    cost: 5,
    strength: 4,
    willpower: 4,
    lore: 2,
    marketPrice: 22.00,
    totalQuantity: 41,
    cardNumber: '118/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Blazing Resurgence',
    abilityText: 'During your turn, whenever another friendly glimmer is banished, this character gains +2 Strength and Challenger +2.',
    flavorText: 'Even the smallest spark can reignite an entire constellation.',
    artId: 'sunlit_dragonling',
    stores: [
      createStoreInventory('store-3', 21.00, 14, 'Near Mint'),
      createStoreInventory('store-1', 22.50, 9, 'Near Mint'),
      createStoreInventory('store-6', 19.50, 12, 'Lightly Played'),
      createStoreInventory('store-2', 24.00, 6, 'Near Mint'),
    ],
  },
  {
    id: 'card-003',
    name: 'Clockwork Sentinel',
    subtitle: 'Ironheart Colossus',
    inkColor: 'Steel',
    rarity: 'Rare',
    cardType: 'Character',
    cost: 6,
    strength: 6,
    willpower: 7,
    lore: 1,
    marketPrice: 14.25,
    totalQuantity: 38,
    cardNumber: '189/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Bodyguard & Resist +1',
    abilityText: 'This character enters play exerted. Opponents must challenge this character if able. Takes 1 less damage from all sources.',
    flavorText: 'Forged in the deep foundry to stand against the ink-flood for centuries.',
    artId: 'clockwork_sentinel',
    stores: [
      createStoreInventory('store-1', 13.50, 11, 'Near Mint'),
      createStoreInventory('store-4', 14.00, 8, 'Near Mint'),
      createStoreInventory('store-2', 15.00, 7, 'Near Mint'),
      createStoreInventory('store-5', 14.50, 12, 'Near Mint'),
    ],
  },
  {
    id: 'card-004',
    name: 'Tidewalker Siren',
    subtitle: 'Reef Singer',
    inkColor: 'Sapphire',
    rarity: 'Super Rare',
    cardType: 'Character',
    cost: 4,
    strength: 2,
    willpower: 5,
    lore: 2,
    marketPrice: 28.00,
    totalQuantity: 19,
    cardNumber: '155/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Ocean Hymn (Singer 6)',
    abilityText: 'This character counts as cost 6 to sing songs. Whenever she sings a song, place the top card of your deck into your inkwell facedown and exerted.',
    flavorText: 'Her melody clears the murky ink, illuminating sunken relics of forgotten realms.',
    artId: 'tidewalker_siren',
    stores: [
      createStoreInventory('store-2', 27.00, 4, 'Near Mint'),
      createStoreInventory('store-3', 28.00, 6, 'Near Mint'),
      createStoreInventory('store-6', 26.50, 5, 'Lightly Played'),
      createStoreInventory('store-1', 29.50, 4, 'Near Mint'),
    ],
  },
  {
    id: 'card-005',
    name: 'Verdant Forest Pathfinder',
    subtitle: 'Ranger of the Brambles',
    inkColor: 'Emerald',
    rarity: 'Uncommon',
    cardType: 'Character',
    cost: 3,
    strength: 3,
    willpower: 3,
    lore: 2,
    marketPrice: 6.80,
    totalQuantity: 62,
    cardNumber: '083/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Evasive Scout',
    abilityText: 'Evasive (Only characters with Evasive can challenge this character). When challenged, you may gain 1 lore.',
    flavorText: '“Step only where the glowing moss thrives, or the shadows will swallow your footsteps.”',
    artId: 'verdant_pathfinder',
    stores: [
      createStoreInventory('store-1', 6.50, 20, 'Near Mint'),
      createStoreInventory('store-4', 6.00, 15, 'Near Mint'),
      createStoreInventory('store-3', 7.00, 18, 'Near Mint'),
      createStoreInventory('store-6', 5.50, 9, 'Lightly Played'),
    ],
  },
  {
    id: 'card-006',
    name: 'Crown Paladin of Light',
    subtitle: 'Vow of the Dawn',
    inkColor: 'Amber',
    rarity: 'Rare',
    cardType: 'Character',
    cost: 4,
    strength: 3,
    willpower: 5,
    lore: 2,
    marketPrice: 16.50,
    totalQuantity: 29,
    cardNumber: '014/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Support & Healing Grace',
    abilityText: 'Support (Whenever this character quests, you may add their Strength to another chosen character’s Strength this turn). Remove up to 2 damage from another character.',
    flavorText: 'An unbreakable shield for every weary ally who walks beside him.',
    artId: 'crown_paladin',
    stores: [
      createStoreInventory('store-2', 15.50, 8, 'Near Mint'),
      createStoreInventory('store-5', 16.00, 7, 'Near Mint'),
      createStoreInventory('store-1', 17.00, 9, 'Near Mint'),
      createStoreInventory('store-4', 16.50, 5, 'Near Mint'),
    ],
  },
  {
    id: 'card-007',
    name: 'Celestial Archive of Spells',
    subtitle: 'Repository of Ancient Glyphs',
    inkColor: 'Sapphire',
    rarity: 'Legendary',
    cardType: 'Item',
    cost: 3,
    marketPrice: 34.00,
    totalQuantity: 15,
    cardNumber: '168/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Scroll Unfurling',
    abilityText: '{Exert}, Pay 2 Ink: Look at the top 3 cards of your deck. Put one into your hand and the rest on the bottom of your deck in any order.',
    flavorText: 'Every parchment whispers secrets of the Great Illuminary.',
    artId: 'celestial_archive',
    stores: [
      createStoreInventory('store-3', 32.50, 4, 'Near Mint'),
      createStoreInventory('store-1', 35.00, 5, 'Near Mint'),
      createStoreInventory('store-2', 34.00, 3, 'Near Mint'),
      createStoreInventory('store-5', 33.00, 3, 'Near Mint'),
    ],
  },
  {
    id: 'card-008',
    name: 'Shadowflame Inversion',
    subtitle: 'Chaotic Surge',
    inkColor: 'Ruby',
    rarity: 'Rare',
    cardType: 'Action',
    cost: 4,
    marketPrice: 11.20,
    totalQuantity: 50,
    cardNumber: '124/204',
    setName: 'First Illumineers Edition',
    abilityName: 'Ember Nova',
    abilityText: 'Deal 3 damage to chosen character. If that character has 5 or more willpower, deal 5 damage instead.',
    flavorText: '“When the fire burns backwards, even obsidian melts into glass.”',
    artId: 'shadowflame_inversion',
    stores: [
      createStoreInventory('store-6', 10.00, 16, 'Near Mint'),
      createStoreInventory('store-1', 11.00, 14, 'Near Mint'),
      createStoreInventory('store-4', 11.50, 8, 'Near Mint'),
      createStoreInventory('store-3', 12.00, 12, 'Near Mint'),
    ],
  },
];
